[target.x86_64-pc-windows-gnu]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-args=-static-libgcc -static-libstdc++"
]

[target.aarch64-pc-windows-gnullvm]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-args=-static-libgcc -static-libstdc++"
]

[build.aarch64-pc-windows-gnullvm]
linker = "aarch64-w64-mingw32-clang++"
ar = "aarch64-w64-mingw32-llvm-ar"

[build.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar = "aarch64-linux-gnu-ar"